name = "ChronologicalCluster"
uuid = "49b0e4c8-e118-4f4b-a916-108c26111553"
authors = ["thiagonovaesb <77932135+Thiago-NovaesB@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
